use super::*;

const COORDINATION_BOARD_ROOT: &str = ".wheeljack/coordination";
pub(crate) const DEFAULT_COORDINATION_TASK_LABEL: &str =
    "Review the shared board and claim work before editing";

const COORDINATION_USER_INSTRUCTION_MARKER: &str = "User instruction:";

#[derive(Debug, Clone, Copy)]
struct Bounds {
    x: f64,
    y: f64,
    height: f64,
}

pub(crate) fn prepare_coordination_prompt(
    nodes: &[CanvasNodeDto],
    node_id: &str,
    workspace_path: &str,
    prompt: &str,
    handoff: &str,
    task_id: Option<&str>,
) -> Result<Value> {
    let node = nodes
        .iter()
        .find(|node| node.id == node_id)
        .ok_or_else(|| anyhow!("coordination prompt node was not found"))?;
    if !is_coordinated_agent_node(node) || contains_coordination_prompt_text(prompt) {
        return Ok(json!({
            "prompt": prompt,
            "wrapped": false,
            "board": Value::Null
        }));
    }

    let cwd = node
        .data
        .get("cwd")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let cwd_key = coordination_path_key(cwd);
    let existing_board = nodes.iter().any(|candidate| {
        coordination_node_board_cwd(candidate)
            .map(|board_cwd| coordination_path_key(board_cwd) == cwd_key)
            .unwrap_or(false)
    });
    let shared_cwd = shared_agent_cwds(nodes)
        .iter()
        .any(|shared| coordination_path_key(shared) == cwd_key);
    if !existing_board && !shared_cwd {
        return Ok(json!({
            "prompt": prompt,
            "wrapped": false,
            "board": Value::Null
        }));
    }

    let board = coordination_board_for_cwd(nodes, cwd, workspace_path);
    let peers = board
        .get("peers")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let peer_rows = peers
        .iter()
        .filter(|peer| peer.get("nodeId").and_then(Value::as_str) != Some(node_id))
        .map(coordination_peer_prompt_row)
        .collect::<Vec<_>>();
    let peer_text = if peer_rows.is_empty() {
        "- No peer agents are currently recorded for this board.".to_string()
    } else {
        peer_rows.join("\n")
    };
    let agents_path = board
        .get("agentsPath")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let agent_log_path = coordination_join_path(
        agents_path,
        &[&format!(
            "{}.ndjson",
            coordination_log_file_stem(&node.title)
        )],
    );
    let task_line = task_id
        .filter(|value| !value.trim().is_empty())
        .map(|value| format!("- wheeljack task id: {}.\n", value.trim()))
        .unwrap_or_default();
    let event_task = coordination_event_task(prompt);
    let wrapped_prompt = format!(
        "{COORDINATION_PROMPT_HEADER}\n- Your callsign is {title}.\n- Your working directory is {cwd}.\n{task_line}- Shared board: {board_path}\n- Shared task projection: {tasks_path}\n- Per-agent event logs: {agents_path}\n- Your agent event log: {agent_log_path}\n\nPeers:\n{peer_text}\n\nWorktree policy:\n- Do not create, remove, switch, or reassign git worktrees unless the user explicitly asks.\n- If peers share your exact cwd, coordinate edits through the board before changing files.\n- If peers are in separate worktrees, treat their work as parallel lanes and keep the board updated with scope, files touched, blockers, and handoff notes.\n- If you need isolation because of overlapping files or risky refactors, propose a worktree split and wait for user approval.\n- Before editing, read the shared task projection and peer event logs for claimed files and active tasks.\n- If a file claim overlaps, negotiate ownership with the peer immediately instead of waiting for a human. The yielding task must publish a new expectedFiles set without the overlapping file; continue only after one owner remains.\n- tasks.md is generated by wheeljack; do not edit it.\n- Append status changes only to your own NDJSON event log. Include taskId, callsign, task, status, expectedFiles, note, and handoff.\n- Only write your own per-agent log file; never write another agent's log.\n\n{COORDINATION_USER_INSTRUCTION_MARKER}\n{prompt}",
        title = node.title,
        cwd = cwd,
        board_path = board
            .get("boardPath")
            .and_then(Value::as_str)
            .unwrap_or_default(),
        tasks_path = board
            .get("tasksPath")
            .and_then(Value::as_str)
            .unwrap_or_default(),
    );
    let callsigns = peers
        .iter()
        .filter_map(|peer| peer.get("callsign").and_then(Value::as_str))
        .collect::<Vec<_>>();
    Ok(json!({
        "prompt": wrapped_prompt,
        "wrapped": true,
        "board": board,
        "ensureRequest": {
            "cwd": cwd,
            "boardId": board.get("boardId").and_then(Value::as_str).unwrap_or_default(),
            "callsigns": callsigns,
            "agentEvent": {
                "callsign": node.title,
                "task": event_task,
                "taskId": task_id,
                "status": "queued",
                "expectedFiles": [],
                "handoff": handoff
            }
        }
    }))
}

fn coordination_peer_prompt_row(peer: &Value) -> String {
    let relation = match peer
        .get("relation")
        .and_then(Value::as_str)
        .unwrap_or_default()
    {
        "same-cwd" => "same cwd",
        "separate-worktree" => "separate worktree lane",
        _ => "other cwd",
    };
    let task = peer
        .get("activeTask")
        .and_then(Value::as_str)
        .filter(|task| !task.is_empty())
        .map(|task| format!(", active task \"{task}\""))
        .unwrap_or_default();
    format!(
        "- {callsign}: {relation}, {cwd}, status {status}{task}",
        callsign = peer
            .get("callsign")
            .and_then(Value::as_str)
            .unwrap_or("Agent"),
        cwd = peer.get("cwd").and_then(Value::as_str).unwrap_or_default(),
        status = peer
            .get("status")
            .and_then(Value::as_str)
            .unwrap_or("unknown"),
    )
}

pub(crate) fn plan_coordination_checklists(
    req: CoordinationChecklistPlanRequest,
) -> Result<CoordinationChecklistPlanResponse> {
    let mut next_nodes = req.nodes;
    let mut created_count = 0usize;
    let mut board_cwds: Vec<(String, String)> = Vec::new();
    let mut board_indexes: HashMap<String, Vec<usize>> = HashMap::new();

    for (index, node) in next_nodes.iter().enumerate() {
        let Some(cwd) = coordination_node_board_cwd(node) else {
            continue;
        };
        let key = coordination_path_key(cwd);
        set_ordered_coordination_cwd(&mut board_cwds, key.clone(), cwd.to_string());
        board_indexes.entry(key).or_default().push(index);
    }
    for cwd in shared_agent_cwds(&next_nodes) {
        set_ordered_coordination_cwd(
            &mut board_cwds,
            coordination_path_key(&cwd),
            cwd.to_string(),
        );
    }

    let mut duplicate_indexes = HashSet::new();
    for (key, cwd) in board_cwds {
        let board = coordination_board_for_cwd(&next_nodes, &cwd, &req.workspace_path);
        let indexes = board_indexes.get(&key).cloned().unwrap_or_default();
        let existing_index = indexes.first().copied();
        if let Some(existing_index) = existing_index {
            let existing = next_nodes[existing_index].clone();
            if existing.kind != "task_checklist" {
                continue;
            }
            let mut merged_items = checklist_items(&existing.data);
            let mut seen_items = merged_items
                .iter()
                .map(coordination_task_merge_key)
                .collect::<HashSet<_>>();
            for duplicate_index in indexes.into_iter().skip(1) {
                let Some(duplicate) = next_nodes.get(duplicate_index) else {
                    continue;
                };
                if duplicate.kind != "task_checklist" {
                    continue;
                }
                duplicate_indexes.insert(duplicate_index);
                for item in checklist_items(&duplicate.data) {
                    let item_key = coordination_task_merge_key(&item);
                    if seen_items.insert(item_key) {
                        merged_items.push(item);
                    }
                }
            }
            let mut updated = existing;
            updated.data = coordination_checklist_data_for_board(board, merged_items);
            updated.updated_at = now();
            next_nodes[existing_index] = updated;
            continue;
        }

        let node = create_coordination_checklist_node(
            &next_nodes,
            &req.canvas_id,
            &cwd,
            &req.workspace_path,
        );
        next_nodes.push(node);
        created_count += 1;
    }

    if !duplicate_indexes.is_empty() {
        next_nodes = next_nodes
            .into_iter()
            .enumerate()
            .filter_map(|(index, node)| (!duplicate_indexes.contains(&index)).then_some(node))
            .collect();
    }

    Ok(CoordinationChecklistPlanResponse {
        nodes: next_nodes,
        created_count,
    })
}

fn set_ordered_coordination_cwd(entries: &mut Vec<(String, String)>, key: String, cwd: String) {
    if let Some((_, existing_cwd)) = entries
        .iter_mut()
        .find(|(existing_key, _)| existing_key == &key)
    {
        *existing_cwd = cwd;
    } else {
        entries.push((key, cwd));
    }
}

fn coordination_node_board_cwd(node: &CanvasNodeDto) -> Option<&str> {
    if node.kind != "task_checklist" {
        return None;
    }
    node.data
        .get("coordination")
        .and_then(|coordination| coordination.get("cwd"))
        .and_then(Value::as_str)
        .filter(|cwd| !cwd.trim().is_empty())
}

fn create_coordination_checklist_node(
    nodes: &[CanvasNodeDto],
    canvas_id: &str,
    cwd: &str,
    workspace_path: &str,
) -> CanvasNodeDto {
    let created_at = now();
    let (x, y) = next_node_position(nodes);
    let board = coordination_board_for_cwd(nodes, cwd, workspace_path);
    let cwd_leaf = cwd_leaf(cwd);
    CanvasNodeDto {
        id: id("node"),
        canvas_id: canvas_id.to_string(),
        kind: "task_checklist".to_string(),
        title: format!("Coordination - {cwd_leaf}"),
        x,
        y,
        width: 460.0,
        height: 360.0,
        z_index: 50 + nodes.len() as i64,
        col_span: None,
        row_span: None,
        single_pane_width: None,
        single_pane_height: None,
        data: coordination_checklist_data_for_board(board, Vec::new()),
        created_at: created_at.clone(),
        updated_at: created_at,
    }
}

fn content_bounds(nodes: &[CanvasNodeDto]) -> Bounds {
    if nodes.is_empty() {
        return Bounds {
            x: -420.0,
            y: -260.0,
            height: 520.0,
        };
    }
    let mut min_x = nodes[0].x;
    let mut min_y = nodes[0].y;
    let mut max_y = nodes[0].y + nodes[0].height;
    for node in nodes.iter().skip(1) {
        let bottom = node.y + node.height;
        if node.x < min_x {
            min_x = node.x;
        }
        if node.y < min_y {
            min_y = node.y;
        }
        if bottom > max_y {
            max_y = bottom;
        }
    }
    Bounds {
        x: min_x,
        y: min_y,
        height: max_y - min_y,
    }
}

fn next_node_position(nodes: &[CanvasNodeDto]) -> (f64, f64) {
    let bounds = content_bounds(nodes);
    let offset = (nodes.len() as f64 * 22.0).min(180.0);
    (
        bounds.x + 120.0_f64.max((nodes.len() % 3) as f64 * 360.0) + offset,
        bounds.y + bounds.height + 48.0 + offset,
    )
}

fn checklist_items(data: &Value) -> Vec<Value> {
    data.get("items")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
}

fn coordination_task_merge_key(item: &Value) -> String {
    let label = item
        .get("label")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .trim();
    let owner = item
        .get("ownerCallsign")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let status = item
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let files = item
        .get("files")
        .and_then(Value::as_array)
        .map(|files| {
            files
                .iter()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(",")
        })
        .unwrap_or_default();
    [label, owner, status, &files].join("\0")
}

fn coordination_checklist_data_for_board(board: Value, current_items: Vec<Value>) -> Value {
    let items = if current_items.is_empty() {
        vec![json!({
            "id": id("task"),
            "label": DEFAULT_COORDINATION_TASK_LABEL,
            "done": false,
            "status": "todo",
            "updatedAt": board
                .get("updatedAt")
                .and_then(Value::as_str)
                .unwrap_or_default()
        })]
    } else {
        current_items
    };
    json!({
        "items": items,
        "coordination": board
    })
}

fn coordination_board_for_cwd(nodes: &[CanvasNodeDto], cwd: &str, workspace_path: &str) -> Value {
    let (board_id, board_path, tasks_path, agents_path) = coordination_board_paths_for_cwd(cwd);
    let peers = nodes
        .iter()
        .filter(|node| is_coordinated_agent_node(node))
        .map(|node| coordination_peer_for_node(node, cwd, workspace_path))
        .collect::<Vec<_>>();
    let same_cwd_count = peers
        .iter()
        .filter(|peer| peer.get("relation").and_then(Value::as_str) == Some("same-cwd"))
        .count();
    json!({
        "boardId": board_id,
        "cwd": cwd,
        "boardPath": board_path,
        "tasksPath": tasks_path,
        "agentsPath": agents_path,
        "mode": if same_cwd_count > 1 { "shared-cwd" } else { "worktree-lanes" },
        "peers": peers,
        "updatedAt": now()
    })
}

fn coordination_peer_for_node(node: &CanvasNodeDto, cwd: &str, workspace_path: &str) -> Value {
    let peer_cwd = node
        .data
        .get("cwd")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let mut peer = serde_json::Map::new();
    peer.insert("nodeId".to_string(), json!(node.id));
    peer.insert("callsign".to_string(), json!(node.title));
    peer.insert("cwd".to_string(), json!(peer_cwd));
    peer.insert(
        "relation".to_string(),
        json!(coordination_relation_for_cwd(cwd, peer_cwd, workspace_path)),
    );
    peer.insert(
        "status".to_string(),
        json!(node
            .data
            .get("status")
            .and_then(Value::as_str)
            .unwrap_or("idle")),
    );
    if let Some(task) = active_task_for_node(node) {
        peer.insert("activeTask".to_string(), json!(task));
    }
    Value::Object(peer)
}

fn active_task_for_node(node: &CanvasNodeDto) -> Option<&str> {
    ["pendingPromptLabel", "pendingPrompt", "prompt"]
        .into_iter()
        .find_map(|key| {
            node.data
                .get(key)
                .and_then(Value::as_str)
                .map(str::trim)
                .filter(|value| !value.is_empty())
        })
}

fn is_coordinated_agent_node(node: &CanvasNodeDto) -> bool {
    node.kind == "agent_terminal"
        && node
            .data
            .get("adapterId")
            .and_then(Value::as_str)
            .unwrap_or_default()
            != "generic-shell"
        && node
            .data
            .get("cwd")
            .and_then(Value::as_str)
            .map(str::trim)
            .is_some_and(|cwd| !cwd.is_empty())
}

fn shared_agent_cwds(nodes: &[CanvasNodeDto]) -> Vec<String> {
    let mut counts: Vec<(String, String, usize)> = Vec::new();
    for node in nodes {
        if !is_coordinated_agent_node(node) {
            continue;
        }
        let cwd = node
            .data
            .get("cwd")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let key = coordination_path_key(cwd);
        if let Some((_, _, count)) = counts
            .iter_mut()
            .find(|(existing_key, _, _)| existing_key == &key)
        {
            *count += 1;
        } else {
            counts.push((key, cwd.to_string(), 1));
        }
    }
    counts
        .into_iter()
        .filter_map(|(_, cwd, count)| (count > 1).then_some(cwd))
        .collect()
}

fn coordination_board_paths_for_cwd(cwd: &str) -> (String, String, String, String) {
    let board_id = format!("cwd_{}", path_hash(&coordination_path_key(cwd)));
    let board_path = coordination_join_path(cwd, &[COORDINATION_BOARD_ROOT, &board_id]);
    let tasks_path = coordination_join_path(&board_path, &["tasks.md"]);
    let agents_path = coordination_join_path(&board_path, &["agents"]);
    (board_id, board_path, tasks_path, agents_path)
}

fn coordination_relation_for_cwd(
    current_cwd: &str,
    peer_cwd: &str,
    workspace_path: &str,
) -> &'static str {
    let current_key = coordination_path_key(current_cwd);
    let peer_key = coordination_path_key(peer_cwd);
    if current_key == peer_key {
        return "same-cwd";
    }
    let current_parent = parent_path_key(current_cwd);
    let peer_parent = parent_path_key(peer_cwd);
    let workspace_parent = parent_path_key(workspace_path);
    if !current_parent.is_empty()
        && current_parent == peer_parent
        && (workspace_parent.is_empty() || workspace_parent == current_parent)
    {
        "separate-worktree"
    } else {
        "other-cwd"
    }
}

fn parent_path_key(value: &str) -> String {
    let normalized = coordination_path_key(value);
    normalized
        .rfind('/')
        .filter(|index| *index > 0)
        .map(|index| normalized[..index].to_string())
        .unwrap_or_default()
}

fn coordination_path_key(value: &str) -> String {
    let normalized = trim_trailing_separators(value)
        .replace('\\', "/")
        .to_lowercase();
    if normalized == "~" || normalized.starts_with("~/") {
        return normalized;
    }
    let bytes = normalized.as_bytes();
    if bytes.len() > 9
        && bytes[1] == b':'
        && bytes[2] == b'/'
        && normalized[3..].starts_with("users/")
    {
        if let Some(home) = collapse_home_suffix(&normalized[9..]) {
            return home;
        }
    }
    if let Some(rest) = normalized.strip_prefix("/users/") {
        if let Some(home) = collapse_home_suffix(rest) {
            return home;
        }
    }
    if let Some(rest) = normalized.strip_prefix("/home/") {
        if let Some(home) = collapse_home_suffix(rest) {
            return home;
        }
    }
    normalized
}

fn collapse_home_suffix(rest: &str) -> Option<String> {
    let (user, tail) = rest.split_once('/').unwrap_or((rest, ""));
    if user.is_empty() {
        return None;
    }
    if tail.is_empty() {
        Some("~".to_string())
    } else {
        Some(format!("~/{tail}"))
    }
}

fn trim_trailing_separators(value: &str) -> String {
    value.trim().trim_end_matches(['/', '\\']).to_string()
}

fn coordination_join_path(base: &str, parts: &[&str]) -> String {
    let separator = if base.contains('\\') { "\\" } else { "/" };
    let clean_base = trim_trailing_separators(base);
    let mut items = Vec::new();
    if !clean_base.is_empty() {
        items.push(clean_base);
    }
    items.extend(
        parts
            .iter()
            .map(|part| part.trim_matches(['/', '\\']))
            .filter(|part| !part.is_empty())
            .map(str::to_string),
    );
    items.join(separator)
}

fn cwd_leaf(cwd: &str) -> String {
    trim_trailing_separators(cwd)
        .rsplit(['/', '\\'])
        .next()
        .filter(|value| !value.is_empty())
        .unwrap_or("cwd")
        .to_string()
}

fn path_hash(value: &str) -> String {
    let mut hash = 5381_u32;
    for ch in value.chars() {
        hash = hash.wrapping_mul(33) ^ ch as u32;
    }
    base36(hash)
}

fn base36(mut value: u32) -> String {
    if value == 0 {
        return "0".to_string();
    }
    const DIGITS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";
    let mut chars = Vec::new();
    while value > 0 {
        chars.push(DIGITS[(value % 36) as usize] as char);
        value /= 36;
    }
    chars.iter().rev().collect()
}

pub(crate) fn ensure_coordination_board(
    req: CoordinationBoardEnsureRequest,
) -> Result<CoordinationBoardFilesDto> {
    let cwd = resolve_workspace_folder_path(&req.cwd)?;
    let board_id = req.board_id.trim();
    if board_id.is_empty()
        || board_id.len() > 80
        || !board_id
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.'))
    {
        bail!("Coordination board id is invalid.");
    }

    let board_path = cwd.join(".wheeljack").join("coordination").join(board_id);
    let agents_path = board_path.join("agents");
    let tasks_path = board_path.join("tasks.md");
    fs::create_dir_all(&agents_path)?;

    let readme_path = board_path.join("README.md");
    if !readme_path.exists() {
        fs::write(
            &readme_path,
            "# wheeljack coordination board\n\nwheeljack generates tasks.md. Agents should read it and append status events only to their own file under agents/.\n",
        )?;
    }
    if !tasks_path.exists() {
        fs::write(
            &tasks_path,
            "# Shared task board\n\n> Generated by wheeljack. Do not edit this file directly.\n",
        )?;
    }

    for callsign in req.callsigns {
        let safe = coordination_log_file_stem(&callsign);
        let log_path = agents_path.join(format!("{safe}.ndjson"));
        if !log_path.exists() {
            fs::write(&log_path, "")?;
        }
    }

    if let Some(event) = req.agent_event {
        append_coordination_agent_event(&agents_path, event)?;
    }

    add_coordination_to_git_exclude(&cwd);

    Ok(CoordinationBoardFilesDto {
        board_id: board_id.to_string(),
        cwd: cwd.to_string_lossy().to_string(),
        board_path: board_path.to_string_lossy().to_string(),
        tasks_path: tasks_path.to_string_lossy().to_string(),
        agents_path: agents_path.to_string_lossy().to_string(),
    })
}

pub(crate) fn sync_coordination_board(
    req: CoordinationBoardSyncRequest,
) -> Result<CoordinationBoardFilesDto> {
    let cwd = resolve_workspace_folder_path(&req.cwd)?;
    let cwd_text = cwd.to_string_lossy().to_string();
    let (board_id, _, _, _) = coordination_board_paths_for_cwd(&cwd_text);
    let files = ensure_coordination_board(CoordinationBoardEnsureRequest {
        cwd: cwd_text,
        board_id,
        callsigns: req.callsigns,
        agent_event: None,
    })?;
    let tasks_path = PathBuf::from(&files.tasks_path);
    promote_generated_file(
        &tasks_path,
        render_coordination_tasks(&req.tasks)?.as_bytes(),
    )?;
    Ok(files)
}

pub(crate) fn read_coordination_board_events(
    req: CoordinationBoardEventsRequest,
) -> Result<CoordinationBoardEventsResponse> {
    let cwd = resolve_workspace_folder_path(&req.cwd)?;
    let cwd_text = cwd.to_string_lossy();
    let (board_id, _, _, _) = coordination_board_paths_for_cwd(&cwd_text);
    let agents_path = cwd
        .join(".wheeljack")
        .join("coordination")
        .join(board_id)
        .join("agents");
    let mut cursors = req.cursors;
    let mut events = Vec::new();
    let mut warnings = Vec::new();
    if !agents_path.exists() {
        return Ok(CoordinationBoardEventsResponse {
            events,
            cursors,
            warnings,
        });
    }

    let mut paths = fs::read_dir(&agents_path)?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(OsStr::to_str) == Some("ndjson"))
        .collect::<Vec<_>>();
    paths.sort();
    for path in paths {
        let Some(file_name) = path.file_name().and_then(OsStr::to_str).map(str::to_string) else {
            continue;
        };
        if fs::metadata(&path)?.len() > 1_048_576 {
            warnings.push(format!(
                "{file_name} exceeds the 1 MiB coordination log limit."
            ));
            continue;
        }
        let bytes = fs::read(&path)?;
        let (content, replaced_invalid_utf8) = match String::from_utf8(bytes) {
            Ok(content) => (content, false),
            Err(error) => (String::from_utf8_lossy(error.as_bytes()).into_owned(), true),
        };
        let lines = content.lines().collect::<Vec<_>>();
        let mut cursor = cursors.get(&file_name).copied().unwrap_or(0);
        if cursor > lines.len() {
            cursor = 0;
            warnings.push(format!(
                "{file_name} was truncated; its event cursor was reset."
            ));
        }
        if replaced_invalid_utf8 && cursor < lines.len() {
            warnings.push(format!(
                "{file_name} contains invalid UTF-8; replacement characters were used."
            ));
        }
        for (index, line) in lines.iter().enumerate().skip(cursor).take(500) {
            match parse_coordination_board_event(&file_name, index, line) {
                Ok(event) => events.push(event),
                Err(error) => warnings.push(format!("{file_name}:{}: {error}", index + 1)),
            }
        }
        cursors.insert(file_name, (cursor + 500).min(lines.len()));
    }
    Ok(CoordinationBoardEventsResponse {
        events,
        cursors,
        warnings,
    })
}

fn render_coordination_tasks(tasks: &[CoordinationTaskDto]) -> Result<String> {
    let mut output = String::from(
        "# Shared task board\n\n> Generated by wheeljack. Agents: append status events to your own file under `agents/`; do not edit this file.\n",
    );
    for (status, heading) in [
        ("queued", "Queued"),
        ("active", "In progress"),
        ("review", "Review"),
        ("done", "Done"),
    ] {
        output.push_str(&format!("\n## {heading}\n\n"));
        for task in tasks.iter().filter(|task| task.status == status) {
            let id = task.id.trim();
            let title = task.title.trim();
            if id.is_empty() || id.len() > 120 || title.is_empty() || title.len() > 500 {
                bail!("Coordination task id/title is invalid.");
            }
            if !id
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.'))
            {
                bail!("Coordination task id is invalid: {id}");
            }
            let checked = if status == "done" { "x" } else { " " };
            let priority = task.priority.trim();
            let priority = if priority.is_empty() {
                "normal"
            } else {
                priority
            };
            let assignees = if task.assignees.is_empty() {
                "Unassigned".to_string()
            } else {
                task.assignees.join(", ")
            };
            output.push_str(&format!(
                "- [{checked}] `{id}` [{}] {} — {}\n",
                markdown_inline(priority),
                markdown_inline(title),
                markdown_inline(&assignees)
            ));
            let detail = task.detail.trim();
            if !detail.is_empty() {
                output.push_str(&format!("  {}\n", markdown_inline(detail)));
            }
        }
    }
    Ok(output)
}

fn markdown_inline(value: &str) -> String {
    value
        .replace(['\r', '\n'], " ")
        .replace('`', "'")
        .trim()
        .to_string()
}

fn promote_generated_file(path: &Path, bytes: &[u8]) -> Result<()> {
    let temp = path.with_extension(format!("tmp-{}", Uuid::now_v7()));
    let backup = path.with_extension("bak");
    fs::write(&temp, bytes)?;
    let _ = fs::remove_file(&backup);
    if path.exists() {
        fs::rename(path, &backup)?;
    }
    if let Err(error) = fs::rename(&temp, path) {
        let _ = fs::rename(&backup, path);
        let _ = fs::remove_file(&temp);
        return Err(error.into());
    }
    let _ = fs::remove_file(backup);
    Ok(())
}

fn parse_coordination_board_event(
    file_name: &str,
    index: usize,
    line: &str,
) -> Result<CoordinationBoardEventDto> {
    if line.len() > 65_536 {
        bail!("event line exceeds 64 KiB");
    }
    let value: Value = serde_json::from_str(line)?;
    let raw_callsign = value
        .get("callsign")
        .and_then(Value::as_str)
        .unwrap_or_else(|| file_name.trim_end_matches(".ndjson"))
        .trim();
    let raw_task = value
        .get("task")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .trim();
    let callsign = truncate_utf8_bytes(raw_callsign, 160);
    let task = truncate_utf8_bytes(raw_task, 4_096);
    let status = value
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or("queued")
        .trim()
        .to_ascii_lowercase();
    if callsign.is_empty() || task.is_empty() {
        bail!("event callsign/task is invalid");
    }
    if !matches!(
        status.as_str(),
        "queued"
            | "running"
            | "in_progress"
            | "review"
            | "needs_input"
            | "blocked"
            | "completed"
            | "done"
            | "failed"
            | "disconnected"
    ) {
        bail!("event status is invalid: {status}");
    }
    let expected_files = value
        .get("expectedFiles")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty() && value.len() <= 1_024)
        .take(64)
        .map(str::to_string)
        .collect();
    let run_id = bounded_string(&value, "runId", 160);
    let progress = parse_coordination_run_progress(value.get("progress"));
    Ok(CoordinationBoardEventDto {
        id: format!("{file_name}:{}", index + 1),
        callsign,
        task,
        task_id: value
            .get("taskId")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty() && value.len() <= 120)
            .map(str::to_string),
        status,
        expected_files,
        note: bounded_optional(&value, "note"),
        handoff: bounded_optional(&value, "handoff"),
        run_id,
        progress,
        timestamp: value
            .get("timestamp")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty() && value.len() <= 80)
            .unwrap_or_default()
            .to_string(),
    })
}

fn parse_coordination_run_progress(value: Option<&Value>) -> Option<CoordinationRunProgressDto> {
    let value = value?.as_object()?;
    let run_id = value.get("runId")?.as_str()?.trim();
    let updated_at = value.get("updatedAt")?.as_str()?.trim();
    let steps = value.get("steps")?.as_array()?;
    if run_id.is_empty()
        || run_id.len() > 160
        || updated_at.is_empty()
        || updated_at.len() > 80
        || steps.len() > 32
    {
        return None;
    }
    let steps = steps
        .iter()
        .map(|step| {
            let id = step.get("id")?.as_str()?.trim();
            let label = step.get("label")?.as_str()?.trim();
            let state = step.get("state")?.as_str()?.trim().to_ascii_lowercase();
            if id.is_empty()
                || id.len() > 120
                || label.is_empty()
                || label.len() > 500
                || !matches!(
                    state.as_str(),
                    "pending" | "running" | "blocked" | "done" | "failed"
                )
            {
                return None;
            }
            Some(CoordinationRunStepDto {
                id: id.to_string(),
                label: label.to_string(),
                state,
            })
        })
        .collect::<Option<Vec<_>>>()?;
    let current_step_id = value
        .get("currentStepId")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|id| steps.iter().any(|step| step.id == *id))
        .map(str::to_string);
    Some(CoordinationRunProgressDto {
        run_id: run_id.to_string(),
        updated_at: updated_at.to_string(),
        current_step_id,
        steps,
    })
}

fn bounded_string(value: &Value, key: &str, max_bytes: usize) -> Option<String> {
    value
        .get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty() && value.len() <= max_bytes)
        .map(str::to_string)
}

fn bounded_optional(value: &Value, key: &str) -> Option<String> {
    value
        .get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty() && value.len() <= 4_096)
        .map(str::to_string)
}

fn truncate_utf8_bytes(value: &str, max_bytes: usize) -> String {
    if value.len() <= max_bytes {
        return value.to_string();
    }
    let end = value
        .char_indices()
        .map(|(index, _)| index)
        .take_while(|index| *index <= max_bytes)
        .last()
        .unwrap_or_default();
    value[..end].to_string()
}

fn coordination_event_task(prompt: &str) -> String {
    let label = prompt
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or(DEFAULT_COORDINATION_TASK_LABEL);
    truncate_utf8_bytes(label.trim(), 500)
}

fn safe_coordination_file_name(value: &str) -> String {
    value
        .trim()
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.') {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches(|ch| matches!(ch, '-' | '_' | '.'))
        .to_string()
}

fn coordination_log_file_stem(value: &str) -> String {
    let safe = safe_coordination_file_name(value);
    if safe.is_empty() {
        "agent".to_string()
    } else {
        safe
    }
}

fn trimmed_optional(value: Option<String>) -> Option<String> {
    value
        .map(|item| item.trim().to_string())
        .filter(|item| !item.is_empty())
}

fn append_coordination_agent_event(
    agents_path: &Path,
    event: CoordinationAgentEventDto,
) -> Result<()> {
    let raw_callsign = event.callsign.trim();
    let safe = coordination_log_file_stem(raw_callsign);
    let callsign = if raw_callsign.is_empty() {
        safe.clone()
    } else {
        truncate_utf8_bytes(raw_callsign, 160)
    };
    let task = truncate_utf8_bytes(event.task.trim(), 4_096);
    if task.is_empty() {
        return Ok(());
    }
    let status = event
        .status
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("queued");
    let expected_files = event
        .expected_files
        .into_iter()
        .map(|file| file.trim().to_string())
        .filter(|file| !file.is_empty())
        .collect::<Vec<_>>();
    let payload = json!({
        "source": "wheeljack",
        "callsign": callsign,
        "status": status,
        "task": task,
        "taskId": trimmed_optional(event.task_id),
        "expectedFiles": expected_files,
        "note": trimmed_optional(event.note),
        "handoff": trimmed_optional(event.handoff),
        "timestamp": now(),
    });
    let line = serde_json::to_string(&payload)?;
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(agents_path.join(format!("{safe}.ndjson")))?;
    writeln!(file, "{line}")?;
    Ok(())
}

fn add_coordination_to_git_exclude(cwd: &Path) {
    if !is_git_repo(cwd) {
        return;
    }
    let output = git_command()
        .arg("-C")
        .arg(cwd)
        .arg("rev-parse")
        .arg("--git-path")
        .arg("info/exclude")
        .output();
    let Ok(output) = output else {
        return;
    };
    if !output.status.success() {
        return;
    }
    let raw_path = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if raw_path.is_empty() {
        return;
    }
    let raw_path = PathBuf::from(raw_path);
    let exclude_path = if raw_path.is_absolute() {
        raw_path
    } else {
        cwd.join(raw_path)
    };
    if let Some(parent) = exclude_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let mut existing = fs::read_to_string(&exclude_path).unwrap_or_default();
    if existing
        .lines()
        .any(|line| line.trim() == ".wheeljack/coordination/")
    {
        return;
    }
    if !existing.ends_with('\n') {
        existing.push('\n');
    }
    existing.push_str(".wheeljack/coordination/\n");
    let _ = fs::write(exclude_path, existing);
}
